<?php /* @var $this Envalo_Widget_Block_Widget_Adminhtml_Shim */ ?>
<?php
    $_additionalEntities = $this->getAdditionalEntitiesAsJson();
?>
<script type="text/javascript">
    WidgetInstance.displayEntityChooser = WidgetInstance.displayEntityChooser.wrap(function (originalCall, type, chooser, additional) {
        var additionalEntities = JSON.parse('<?php echo $_additionalEntities; ?>');

        if (!additionalEntities.hasOwnProperty(type)) {
            originalCall(type, chooser, additional);
        } else {
            if (!additional) {
                additional = {};
            }

            additional.url = additionalEntities[type]['url'];
            additional.post_parameters = $H({});
            WidgetInstance.displayChooser(chooser, additional);
        }
    });

    WidgetInstance.displayPageGroup = function (container, additional) {
        container = $(container);
        if (!container) {}

        if (!additional) {
            additional = {};
        }

        if (activePageGroupId = this.activePageGroups.get(container.up('div.page_group_container').id)) {
            this.hideBlockContainer(activePageGroupId);
        }

        this.activePageGroups.set(container.up('div.page_group_container').id, container.id);
        this.showBlockContainer(container);

        var blockContainer = container.down('div.block_reference');

        if (blockContainer && blockContainer.innerHTML == '') {
            var layoutHandle = '';
            var layoutHandleField = container.down('input.layout_handle_pattern');

            if (layoutHandleField) {
                layoutHandle = layoutHandleField.value;
            } else if (layoutHandleField = container.down('select#layout_handle')) {
                layoutHandle = layoutHandleField.value;
            }

            this.loadSelectBoxByType('block_reference', container, layoutHandle, additional);
        }
        this.loadSelectBoxByType('block_template', container, additional.selectedBlock, additional);
    }
</script>